version: '2'
services:
     goessinger.eu:
          container_name: "goessinger.eu"
          image: "webdevops/apache:alpine"
          volumes:
          - ../goessinger.eu/html/:/app
          ports:
          - "1080:80"
          - "1443:443"
          restart: "always"
          environment:
          - VIRTUAL_HOST=goessinger.eu
     sabnzbd:
          container_name: "sabnzbd"
          image: linuxserver/sabnzbd:latest
          volumes:
          - ../sabnzbd/config:/config
          - ../sabnzbd/complete:/downloads
          - ../sabnzbd/incomplete:/incomplete-downloads
          ports:
          - "5080:8080"
          - "5090:8090"
          environment:
          - PGID=0
          - PUID=0
          - TZ=Europe/Berlin
          - VIRTUAL_HOST=sabnzbd.goessinger.eu
          - VIRTUAL_PORT=8080
          restart: "always"
     birding:
          container_name: "birding"
          build: ../birding/.
          volumes:
          - ../birding/html/:/app
          - ../birding/scripts:/scripts
          restart: "always"
          network_mode: "host"
     birding_web:
          container_name: "birding_web"
          image: "webdevops/apache:alpine"
          volumes:
          - ../birding/html/:/app
          ports:
          - "6080:80"
          - "6443:443"
          restart: "always"
          environment:
          - VIRTUAL_HOST=birding.goessinger.eu
     proxy:
          image: jwilder/nginx-proxy:alpine
          container_name: proxy
          ports:
          - "80:80"
          restart: "always"
          volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
     mysql:
          image: mysql:latest
          container_name: mysql
          environment:
          - MYSQL_ROOT_PASSWORD=test #this will be changed
          volumes:
          - ../mysql/data/:/var/lib/mysql
     phpmyadmin:
          image: phpmyadmin/phpmyadmin:latest
          container_name: phpmyadmin
          environment:
          - PMA_ARBITRARY=1
          ports:
          - 8080:80
          volumes:
          - /sessions
          links:
          - mysql:mysql
     crawler:
          build: ../ornitho-crawler/.
          container_name: ornitho-crawler
          links:
          - mysql:mysql
     tensorflow:
          image: gcr.io/tensorflow/tensorflow:latest-devel
          container_name: tensorflow
          volumes:
          - ../tensorflow_data/:/data
          restart: "always"